server:
  address: 127.0.0.1
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 8244
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    generate-ddl: true
    show-ddl: true
    defer-datasource-initialization: true
    show-sql: true

  thymeleaf:
    enabled: false

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
  com.amazonaws.util.EC2MetadataUtils: error
